"""Add isEmailVerified column to users table

Revision ID: 2b1bb6886905
Revises: 0ea58def0ee0
Create Date: 2026-02-12 12:51:03.750588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1bb6886905'
down_revision: Union[str, Sequence[str], None] = '0ea58def0ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isEmailVerified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isEmailVerified')
    # ### end Alembic commands ###
