"""consistent naming convention

Revision ID: a457f94a617e
Revises: 2b1bb6886905
Create Date: 2026-02-12 13:20:26.746982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a457f94a617e'
down_revision: Union[str, Sequence[str], None] = '2b1bb6886905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'isEmailVerified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isEmailVerified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
